name: 'outputs-workflow'
on:
  workflow_dispatch:
  release:
    types: 
      - created
jobs:
  outputs:
    name: Show Outputs
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: show output
        run: |
        echo $(git rev-parse --short HEAD)